### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by ianneub** [tutumcloud/tutum-docker-clusterproxy#25]
The default options for HAProxy include httplog, but I don't see a way to get the log data out of the container.

How would one get access to those logs?

Maybe we can watch the log file and pipe it to stdout?

**Comment by tifayuki** [comment]
Hi @ianneub ,

You can use volume to to access the http log.

If you run haproxy with `-v /var/log/haproxy.log:/var/log/haproxy.log`, you can find the http log file(/var/log/haproxy.log) on your host.

Also you can run the container with `--volumes-from`, so that you can process the log file in another container.

**Comment by motin** [comment]
Please re-open, it is way to complicated to access the logs currently. Also, it is not a good idea that local log files are in use since they may fill up the container. 

The Docker way is to pipe logs to stdout and then let for instance logspout or some other container forward the logs to a remote syslog.

PS Tried following the advice here by first running the tutum/haproxy image with `-v /var/log/haproxy.log` and then running (replaced 54545 with our specific papertrailapp port of course):

     docker run -d --volumes-from haproxy andyshinn/remote_syslog2 -d logs.papertrailapp.com -p 54545 /var/log/haproxy.log

So far, nothing has shown up in papertrailapp, without any obvious problem reported in the collector's logs.

**Comment by fermayo** [comment]
@motin you are right, the "docker-way" is to pipe them to stdout and then forward them to a logging service as other container's logs will be sent.
@tifayuki can we log to stdout instead? we have to log changes to the configuration in some other way though...

**Comment by motin** [comment]
> we have to log changes to the configuration in some other way though...
That should also be piped to stdout.

**Comment by kytwb** [comment]
:+1: for piping to stdout.
